#!/bin/sh
ssh ec2-52-45-170-173.compute-1.amazonaws.com <<EOF
    cd ~/MyTestNodeJS
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF
